### ISSUE TITLE
运行unitTestInfo.rb报错

### ISSUE THREAD

**Issue by YiFan-Tong** [JerryChu/UnitTestParser#1]
macOS Catalina：10.15.3
xcode：11.4.1
python：Python 2.7.15

------------------------终端返回信息---------------------
Traceback (most recent call last):
        5: from /Users/mac126/Desktop/WhaleUnitTestDemo/TestScript/unitTestInfo.rb:134:in `<main>'
        4: from /Users/mac126/Desktop/WhaleUnitTestDemo/TestScript/unitTestInfo.rb:47:in `parse_xcresult'
        3: from /Users/mac126/Desktop/WhaleUnitTestDemo/TestScript/unitTestInfo.rb:103:in `generate_summary_object'
        2: from /Users/mac126/Desktop/WhaleUnitTestDemo/TestScript/unitTestInfo.rb:103:in `each'
        1: from /Users/mac126/Desktop/WhaleUnitTestDemo/TestScript/unitTestInfo.rb:106:in `block in generate_summary_object'
/Users/mac126/Desktop/WhaleUnitTestDemo/TestScript/unitTestInfo.rb:106:in `+': nil can't be coerced into Float (TypeError)

------------------------分割线---------------------------

以上应该是警告之类的，因为后面的命令行还能进行，并且能正常输出test-coverage-result.html

targetCoverage.rb有同样的情况，这个有什么方法能改善吗？还是说我Python或者其他什么工具环境版本不对？？？

**Comment by JerryChu** [comment]
出错行：https://github.com/JerryChu/UnitTestParser/blob/master/unitTestInfo.rb#L106
应该是xcresult文件有问题，看下是否是单元测试执行出错了。

可以用 https://github.com/JerryChu/UnitTestDemo 工程试一下脚本能否正常执行。

另外，脚本为ruby脚本，和python版本无关。

**Comment by YiFan-Tong** [comment]
> 出错行：https://github.com/JerryChu/UnitTestParser/blob/master/unitTestInfo.rb#L106
> 应该是xcresult文件有问题，看下是否是单元测试执行出错了。
> 
> 可以用 https://github.com/JerryChu/UnitTestDemo 工程试一下脚本能否正常执行。
> 
> 另外，脚本为ruby脚本，和python版本无关。

好的，我再试试，谢谢你
