### ISSUE TITLE
你好，请问./test.sh之后代码覆盖率部分的代码好像有问题

### ISSUE THREAD

**Issue by Louis-LYK** [JerryChu/UnitTestParser#3]
![image](https://user-images.githubusercontent.com/33407710/122149705-19987880-ce8f-11eb-98da-39ecb30f3c1c.png)

![image](https://user-images.githubusercontent.com/33407710/122149768-33d25680-ce8f-11eb-9e6b-9f8d879aca49.png)
你好，我这边在做代码覆盖率测试的时候，代码出现问题，首先是报错，如图一，我通过定位bug发现是在图二上，就是这里在解析方法中引入的json是一个空文件，什么都没有，导致了报错，请问这里该怎么解决呢？

**Comment by Louis-LYK** [comment]
@JerryChu 作者你好，我再整理一下我的问题。
我这里想要得到代码覆盖率的解析数据，因此我推测问题是出在下图所示的地方：
![image](https://user-images.githubusercontent.com/33407710/122150665-b7d90e00-ce90-11eb-9a01-84407c091f6a.png)
--cov-json-path="${XctestResultJSONPath}把它摘出来，即这个路径是的地址是ResultBundlePath="${TEST_PATH}/CoverageJSON"，但是目前CoverageJSON是一个空文件，这导致了出现了如我上面提交issue的那个报错代码，parse_xcresult_json尝试去读取空文件的json，就报错了。

**Comment by JerryChu** [comment]
可以再往上游打些日志，看下是不是单元测试执行过程出问题了，有没有生成 _xcresult_ 文件。

**Comment by Louis-LYK** [comment]
> 可以再往上游打些日志，看下是不是单元测试执行过程出问题了，有没有生成 _xcresult_ 文件。

xcresult文件成功生成了，然后unittesstinfo成功跑通，如下两图：
![image](https://user-images.githubusercontent.com/33407710/122177467-39906200-ceb8-11eb-84ef-53cc0315a97d.png)
![image](https://user-images.githubusercontent.com/33407710/122178037-c804e380-ceb8-11eb-8c02-0fe1817c677c.png)
可以看到第一个测试已经跑出结果来了，但是出现了红框中的bug，这一块，我认为可能是问题在xccov这里，我第一次写这个程序对这个命令还不太熟，不知道作者您是否遇到这类报错？是否可能是xccov版本老需要更新，或者是需要其他的插件呢？

**Comment by JerryChu** [comment]
![image](https://user-images.githubusercontent.com/4471501/122330173-44550080-cf65-11eb-918e-70107aeacc37.png)
这里看是单元测试失败了？ 看下这个路径 *XctestResultFilePath* 下是 xcresult 文件吗？

**Comment by Louis-LYK** [comment]
> ![image](https://user-images.githubusercontent.com/4471501/122330173-44550080-cf65-11eb-918e-70107aeacc37.png)
> 这里看是单元测试失败了？ 看下这个路径 _XctestResultFilePath_ 下是 xcresult 文件吗？

是的，作者，是xcresult文件：
![image](https://user-images.githubusercontent.com/33407710/122899638-93909c00-d37e-11eb-928a-586d4193bb7b.png)
用xcode打开后是这样：
![image](https://user-images.githubusercontent.com/33407710/122899935-d5214700-d37e-11eb-9569-b3892316c49d.png)

**Comment by Louis-LYK** [comment]
> ![image](https://user-images.githubusercontent.com/4471501/122330173-44550080-cf65-11eb-918e-70107aeacc37.png)
> 这里看是单元测试失败了？ 看下这个路径 _XctestResultFilePath_ 下是 xcresult 文件吗？

test failed这个报错，请问改如何定位该问题，是在哪个情况下发生的，跟xcresult里testWrong有关吗？

**Comment by JerryChu** [comment]
可以先把 *testWrong* 修复了，所有单元测试都跑成功后再看下。

**Comment by JerryChu** [comment]
没有其他问题的话我先close了。
