### ISSUE TITLE
Jerry大师你好，我可以对 `diffParser.rb` 进行二次开发吗？

### ISSUE THREAD

**Issue by erduoniba** [JerryChu/UnitTestParser#4]
如题，`diffParser.rb` 会统计每个改动文件，但是往往开发关注的只是代码相关的改动。比如iOS开发，只需要关注与 '.m' 、'.mm'、'.swift' 格式。

**Comment by JerryChu** [comment]
`diffParser` 传入的是单个diff文件，而不是代码文件，如果只关注 .m/.mm/.swift，应该在更上层做处理。

当然，有任何自定义需求可以fork一份直接修改，如果是通用能力，欢迎提PR～
