### ISSUE TITLE
diffParser.rb解析结果为空 

### ISSUE THREAD

**Issue by GE-GAO-ZHAO** [JerryChu/UnitTestParser#5]
我的解析目录如下
![Xnip2023-11-14_17-01-18](https://github.com/JerryChu/UnitTestParser/assets/66877871/5ed1b5bf-f727-4079-975e-5c06ce4b099a)

1820141.diff信息如下
```
diff --git a/Example/GZCodeCoverageKit/Source/TestSwift.swift b/Example/GZCodeCoverageKit/Source/TestSwift.swift
index 15e3a65..2f1d445 100644
--- a/Example/GZCodeCoverageKit/Source/TestSwift.swift
+++ b/Example/GZCodeCoverageKit/Source/TestSwift.swift
@@ -23,3 +22,0 @@ class TestSwift {
-        print("hello, i`m test22 嘻嘻嘻")
-        print("hello, i`m test22 嘻嘻嘻")
-        print("hello, i`m test22 嘻嘻嘻")
```

但是执行 ruby GitdiffUtils/utils/diffParser.rb --diff-file=1820141.diff 结果如下
```
{"Example/GZCodeCoverageKit/Source/TestSwift.swift"=>[]}
```
里面的修改信息为空

辛苦大佬帮忙看下

**Comment by GE-GAO-ZHAO** [comment]
![Xnip2023-11-14_17-27-33](https://github.com/JerryChu/UnitTestParser/assets/66877871/bd57dfe7-e30e-4f55-bc33-9c044dcadbe3)
这个rb文件怎么在工程找不到 大佬

**Comment by JerryChu** [comment]
> 我的解析目录如下 ![Xnip2023-11-14_17-01-18](https://private-user-images.githubusercontent.com/66877871/282719682-5ed1b5bf-f727-4079-975e-5c06ce4b099a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDMzOTQsIm5iZiI6MTcwNDQ0MzA5NCwicGF0aCI6Ii82Njg3Nzg3MS8yODI3MTk2ODItNWVkMWI1YmYtZjcyNy00MDc5LTk3NWUtNWMwNmNlNGIwOTlhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMGMwZThkMjBjZDllOWU5NjhiYWEwMTU3NDJkMjk0NWZiOGQwNTE0OGQ5MjY1YjE5MjczNTlhODFlYTRkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0S9xmV2mkCULlB4gn5TtX7pFsC2xEjnkEfgMJTddH-8)
> 
> 1820141.diff信息如下
> 
> ```
> diff --git a/Example/GZCodeCoverageKit/Source/TestSwift.swift b/Example/GZCodeCoverageKit/Source/TestSwift.swift
> index 15e3a65..2f1d445 100644
> --- a/Example/GZCodeCoverageKit/Source/TestSwift.swift
> +++ b/Example/GZCodeCoverageKit/Source/TestSwift.swift
> @@ -23,3 +22,0 @@ class TestSwift {
> -        print("hello, i`m test22 嘻嘻嘻")
> -        print("hello, i`m test22 嘻嘻嘻")
> -        print("hello, i`m test22 嘻嘻嘻")
> ```
> 
> 但是执行 ruby GitdiffUtils/utils/diffParser.rb --diff-file=1820141.diff 结果如下
> 
> ```
> {"Example/GZCodeCoverageKit/Source/TestSwift.swift"=>[]}
> ```
> 
> 里面的修改信息为空
> 
> 辛苦大佬帮忙看下


> ```
> @@ -23,3 +22,0 @@ class TestSwift {
> -        print("hello, i`m test22 嘻嘻嘻")
> -        print("hello, i`m test22 嘻嘻嘻")
> -        print("hello, i`m test22 嘻嘻嘻")
> ```



> 我的解析目录如下 ![Xnip2023-11-14_17-01-18](https://private-user-images.githubusercontent.com/66877871/282719682-5ed1b5bf-f727-4079-975e-5c06ce4b099a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NDMzOTQsIm5iZiI6MTcwNDQ0MzA5NCwicGF0aCI6Ii82Njg3Nzg3MS8yODI3MTk2ODItNWVkMWI1YmYtZjcyNy00MDc5LTk3NWUtNWMwNmNlNGIwOTlhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA4MjQ1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMGMwZThkMjBjZDllOWU5NjhiYWEwMTU3NDJkMjk0NWZiOGQwNTE0OGQ5MjY1YjE5MjczNTlhODFlYTRkZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0S9xmV2mkCULlB4gn5TtX7pFsC2xEjnkEfgMJTddH-8)
> 
> 1820141.diff信息如下
> 
> ```
> diff --git a/Example/GZCodeCoverageKit/Source/TestSwift.swift b/Example/GZCodeCoverageKit/Source/TestSwift.swift
> index 15e3a65..2f1d445 100644
> --- a/Example/GZCodeCoverageKit/Source/TestSwift.swift
> +++ b/Example/GZCodeCoverageKit/Source/TestSwift.swift
> @@ -23,3 +22,0 @@ class TestSwift {
> -        print("hello, i`m test22 嘻嘻嘻")
> -        print("hello, i`m test22 嘻嘻嘻")
> -        print("hello, i`m test22 嘻嘻嘻")
> ```
> 
> 但是执行 ruby GitdiffUtils/utils/diffParser.rb --diff-file=1820141.diff 结果如下
> 
> ```
> {"Example/GZCodeCoverageKit/Source/TestSwift.swift"=>[]}
> ```
> 
> 里面的修改信息为空
> 
> 辛苦大佬帮忙看下

`diffParser.rb` 仅解析增加代码行，你的 diff 文件中增加代码行为0，所以输出为空。

> @@ -23,3 +22,0 @@
